### ISSUE TITLE
Docker build failing

### ISSUE THREAD

**Issue by somenewaccountthen** [jbilcke-hf/FacePoke#29]
The docker build fails with an error **see bottom**.

docker build -t facepoke .

This is the output: 
[+] Building 204.7s (13/15)                                     docker:default
 => [internal] load build definition from Dockerfile                      0.0s
 => => transferring dockerfile: 1.31kB                                    0.0s
 => [internal] load metadata for docker.io/nvidia/cuda:12.4.0-devel-ubun  1.5s
 => [auth] nvidia/cuda:pull token for registry-1.docker.io                0.0s
 => [internal] load .dockerignore                                         0.0s
 => => transferring context: 357B                                         0.0s
 => [ 1/10] FROM docker.io/nvidia/cuda:12.4.0-devel-ubuntu22.04@sha256  145.5s
 => => resolve docker.io/nvidia/cuda:12.4.0-devel-ubuntu22.04@sha256:283  0.0s
 => => sha256:14c54fad24b376ab78a70e1ef6595a2b7c8cdbf187 2.63kB / 2.63kB  0.0s
 => => sha256:28326fefd36d43ecf82447e9ca1175db639b931e234019 743B / 743B  0.0s
 => => sha256:899566afc09ee8b407db43928e3e7882092f0f4c 18.12kB / 18.12kB  0.0s
 => => sha256:bccd10f490ab0f3fba61b193d1b80af91b17ca9b 29.54MB / 29.54MB  2.9s
 => => sha256:e06eb1b5c4cc0283389710e45402738c973f9c27 57.59MB / 57.59MB  2.1s
 => => sha256:edd1dba56169c724e9377dafe9d6dd34c0ef958510 4.62MB / 4.62MB  0.4s
 => => sha256:7f308a7652768c0a964eb1720554421079b6a956110c7a 184B / 184B  0.7s
 => => sha256:3af11d09e9cd1eb9c379f0a4071231e5a5642eb728 6.88kB / 6.88kB  1.2s
 => => sha256:42896cdfd7b6a3e75be89e9fbc327a2dc8a1f56ab 1.36GB / 1.36GB  71.0s
 => => sha256:6005190795580507557f886a8cb09d07f48a2935 64.06kB / 64.06kB  2.3s
 => => sha256:0ae42424cadfa646dc06982b0ed3d08688b628c43f 1.69kB / 1.69kB  2.5s
 => => sha256:73b7968785dcb3e277c8de18c033614246b9419edb 1.52kB / 1.52kB  2.7s
 => => sha256:80150f70fb1e403d909539844a70fcb152ecfbd99 2.63GB / 2.63GB  92.7s
 => => extracting sha256:bccd10f490ab0f3fba61b193d1b80af91b17ca9bdca9768  0.9s
 => => sha256:3bd5db8307cf789162a5a096889ea97023d57950 88.90kB / 88.90kB  3.0s
 => => extracting sha256:edd1dba56169c724e9377dafe9d6dd34c0ef9585109fa83  0.1s
 => => extracting sha256:e06eb1b5c4cc0283389710e45402738c973f9c27a4cbdf9  1.5s
 => => extracting sha256:7f308a7652768c0a964eb1720554421079b6a956110c7a1  0.0s
 => => extracting sha256:3af11d09e9cd1eb9c379f0a4071231e5a5642eb728b4b33  0.0s
 => => extracting sha256:42896cdfd7b6a3e75be89e9fbc327a2dc8a1f56ab23a99  15.2s
 => => extracting sha256:6005190795580507557f886a8cb09d07f48a293591caa5f  0.0s
 => => extracting sha256:0ae42424cadfa646dc06982b0ed3d08688b628c43fc3797  0.0s
 => => extracting sha256:73b7968785dcb3e277c8de18c033614246b9419edb40941  0.0s
 => => extracting sha256:80150f70fb1e403d909539844a70fcb152ecfbd994a2c2  52.6s
 => => extracting sha256:3bd5db8307cf789162a5a096889ea97023d5795068bdd8f  0.0s
 => [internal] load build context                                         0.0s
 => => transferring context: 1.99MB                                       0.0s
 => [ 2/10] RUN apt-get update && apt-get install --no-install-recommen  32.1s
 => [ 3/10] WORKDIR /code                                                 0.0s
 => [ 4/10] COPY ./requirements.txt /code/requirements.txt                0.0s
 => [ 5/10] RUN echo "Installing pget" &&     curl -o /usr/local/bin/pge  0.4s
 => [ 6/10] RUN useradd -m -u 1000 user                                   0.2s
 => [ 7/10] RUN echo "Installing requirements.txt"                        0.2s
 => ERROR [ 8/10] RUN pip3 install --no-cache-dir --upgrade -r /code/re  24.6s
------
 > [ 8/10] RUN pip3 install --no-cache-dir --upgrade -r /code/requirements.txt:
0.453 Defaulting to user installation because normal site-packages is not writeable
0.484 Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu124
1.274 Collecting torch
1.297   Downloading https://download.pytorch.org/whl/cu124/torch-2.5.1%2Bcu124-cp310-cp310-linux_x86_64.whl (908.3 MB)
20.52      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 908.3/908.3 MB 46.8 MB/s eta 0:00:00
21.86 Collecting torchvision
21.87   Downloading https://download.pytorch.org/whl/cu124/torchvision-0.20.1%2Bcu124-cp310-cp310-linux_x86_64.whl (7.3 MB)
22.05      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.3/7.3 MB 42.2 MB/s eta 0:00:00
22.60 Collecting torchaudio
22.61   Downloading https://download.pytorch.org/whl/cu124/torchaudio-2.5.1%2Bcu124-cp310-cp310-linux_x86_64.whl (3.4 MB)
22.68      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 46.2 MB/s eta 0:00:00
23.20 Collecting torchgeometry
23.29   Downloading torchgeometry-0.1.2-py2.py3-none-any.whl (42 kB)
23.30      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.7/42.7 KB 3.1 MB/s eta 0:00:00
23.69 Collecting async-lru==2.0.4
23.70   Downloading async_lru-2.0.4-py3-none-any.whl (6.1 kB)
24.29 ERROR: Could not find a version that satisfies the requirement gradio==5.0.0b4 (from versions: 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5, 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.2.0, 0.2.1, 0.3.0, 0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.3.5, 0.4.0, 0.4.1, 0.4.2, 0.4.4, 0.5.0, 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.7.4, 0.7.5, 0.7.6, 0.7.7, 0.7.8, 0.8.0, 0.8.1, 0.9.0, 0.9.1, 0.9.2, 0.9.3, 0.9.4, 0.9.5, 0.9.6, 0.9.7, 0.9.8, 0.9.9.2, 0.9.9.3, 0.9.9.5, 0.9.9.6, 0.9.9.7, 0.9.9.8, 0.9.9.9, 0.9.9.9.2, 1.0.0a1, 1.0.0a3, 1.0.0a4, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.7, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.1.6, 1.1.8, 1.1.8.1, 1.1.9, 1.2.2, 1.2.3, 1.3.0, 1.3.1, 1.3.2, 1.4.0, 1.4.2, 1.4.3, 1.4.4, 1.5.0, 1.5.1, 1.5.3, 1.5.4, 1.6.0, 1.6.1, 1.6.2, 1.6.3, 1.6.4, 1.7.0, 1.7.1, 1.7.2, 1.7.3, 1.7.4, 1.7.5, 1.7.6, 1.7.7, 2.0.0, 2.0.1, 2.0.2, 2.0.4, 2.0.5, 2.0.6, 2.0.7, 2.0.8, 2.0.9, 2.0.10, 2.1.0, 2.1.1, 2.1.2, 2.1.4, 2.1.6, 2.1.7, 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.2.4, 2.2.5, 2.2.6, 2.2.7, 2.2.8, 2.2.9a0, 2.2.9a2, 2.2.10, 2.2.11, 2.2.12, 2.2.13, 2.2.14, 2.2.15, 2.3.0a0, 2.3.0b99, 2.3.0b101, 2.3.0b102, 2.3.0, 2.3.3, 2.3.4, 2.3.5b0, 2.3.5, 2.3.6, 2.3.7b0, 2.3.7b1, 2.3.7b2, 2.3.7, 2.3.8b0, 2.3.9, 2.4.0a0, 2.4.0, 2.4.1, 2.4.2, 2.4.4, 2.4.5, 2.4.6, 2.4.7b0, 2.4.7b2, 2.4.7b3, 2.4.7b4, 2.4.7b5, 2.4.7b6, 2.4.7b7, 2.4.7b8, 2.4.7b9, 2.5.0, 2.5.1, 2.5.2, 2.5.3, 2.5.8a0, 2.6.0, 2.6.1a0, 2.6.1b0, 2.6.1b3, 2.6.1, 2.6.2, 2.6.3, 2.6.4b0, 2.6.4b2, 2.6.4b3, 2.6.4, 2.7.0a101, 2.7.0a102, 2.7.0b70, 2.7.0, 2.7.5, 2.7.5.1, 2.7.5.2b0, 2.7.5.2, 2.8.0a100, 2.8.0b0, 2.8.0b2, 2.8.0b3, 2.8.0b4, 2.8.0b5, 2.8.0b6, 2.8.0b10, 2.8.0b12, 2.8.0b20, 2.8.0b22, 2.8.0, 2.8.1, 2.8.2, 2.8.3, 2.8.4, 2.8.5, 2.8.6, 2.8.7, 2.8.8, 2.8.9, 2.8.10, 2.8.11, 2.8.12, 2.8.13, 2.8.14, 2.9.0b0, 2.9.0b1, 2.9.0b2, 2.9.0b3, 2.9.0b5, 2.9.0b6, 2.9.0b7, 2.9.0b8, 2.9.0b9, 2.9.0b10, 2.9b11, 2.9b12, 2.9b13, 2.9b14, 2.9b15, 2.9b20, 2.9b21, 2.9b22, 2.9b23, 2.9b24, 2.9b25, 2.9b26, 2.9b27, 2.9b28, 2.9b30, 2.9b31, 2.9b32, 2.9b33, 2.9b40, 2.9b48, 2.9b50, 2.9.0, 2.9.0.1, 2.9.1, 2.9.2, 2.9.3, 2.9.4, 3.0b0, 3.0b1, 3.0b2, 3.0b5, 3.0b6, 3.0b8, 3.0b9, 3.0b10, 3.0, 3.0.1b120, 3.0.1b121, 3.0.1b300, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.0.6b1, 3.0.6b2, 3.0.6b3, 3.0.6, 3.0.7, 3.0.8b1, 3.0.8, 3.0.9b10, 3.0.9b11, 3.0.9b20, 3.0.9, 3.0.10b2, 3.0.10b16, 3.0.10, 3.0.11b1, 3.0.11, 3.0.12, 3.0.13b13, 3.0.13b15, 3.0.13b100, 3.0.13, 3.0.14, 3.0.15, 3.0.16, 3.0.17, 3.0.18b0, 3.0.18, 3.0.19b0, 3.0.19b1, 3.0.19b2, 3.0.19, 3.0.20.dev0, 3.0.20, 3.0.21, 3.0.22, 3.0.23.dev1, 3.0.23, 3.0.24, 3.0.25, 3.0.26, 3.1.0, 3.1.1, 3.1.2, 3.1.3a0, 3.1.3a2, 3.1.3a3, 3.1.3a4, 3.1.3a5, 3.1.3, 3.1.4b0, 3.1.4b1, 3.1.4b2, 3.1.4b3, 3.1.4b4, 3.1.4b5, 3.1.4, 3.1.5b1, 3.1.5b2, 3.1.5b3, 3.1.5b4, 3.1.5b5, 3.1.5b7, 3.1.5b8, 3.1.5b9, 3.1.5b10, 3.1.5, 3.1.6b1, 3.1.6, 3.1.7, 3.1.8b0, 3.1.8b2, 3.1.8b3, 3.1.8b4, 3.1.8b6, 3.2, 3.2.1b0, 3.2.1b1, 3.2.1b2, 3.3b0, 3.3b1, 3.3, 3.3.1, 3.4b0, 3.4b1, 3.4b2, 3.4b3, 3.4b5, 3.4, 3.4.1, 3.5, 3.6.0b1, 3.6.0b2, 3.6.0b3, 3.6.0b7, 3.6.0b10, 3.6, 3.7, 3.8b1, 3.8b2, 3.8, 3.8.1.dev1, 3.8.1, 3.8.2, 3.9, 3.9.1, 3.10.0, 3.10.1, 3.11.0, 3.12.0b1, 3.12.0b2, 3.12.0b3, 3.12.0b6, 3.12.0b7, 3.12.0, 3.13.0b1, 3.13.0, 3.13.1b0, 3.13.1b1, 3.13.1b2, 3.13.1, 3.13.2, 3.14.0a1, 3.14.0, 3.15.0, 3.16.0, 3.16.1b1, 3.16.1, 3.16.2, 3.17.0, 3.17.1b1, 3.17.1b2, 3.17.1, 3.18.0, 3.18.1b1, 3.18.1b2, 3.18.1b3, 3.18.1b4, 3.18.1b5, 3.18.1b6, 3.18.1b7, 3.19.0, 3.19.1, 3.20.0b1, 3.20.0b2, 3.20.0, 3.20.1, 3.21.0, 3.22.0, 3.22.1b1, 3.22.1, 3.23.0, 3.23.1b1, 3.23.1b2, 3.23.1b3, 3.24.0, 3.24.1, 3.25.0, 3.25.1b1, 3.25.1b2, 3.26.0, 3.27.0, 3.28.0, 3.28.1, 3.28.2, 3.28.3, 3.28.4b0, 3.29.0, 3.30.0, 3.31.0, 3.32.0, 3.33.0, 3.33.1, 3.34.0, 3.35.0, 3.35.1, 3.35.2, 3.36.0, 3.36.1, 3.37.0, 3.38.0, 3.39.0, 3.40.0, 3.40.1, 3.41.0, 3.41.1, 3.41.2, 3.42.0, 3.43.0, 3.43.1, 3.43.2, 3.44.0, 3.44.1, 3.44.2, 3.44.3, 3.44.4, 3.45.0b0, 3.45.0b1, 3.45.0b2, 3.45.0b3, 3.45.0b4, 3.45.0b5, 3.45.0b6, 3.45.0b7, 3.45.0b8, 3.45.0b9, 3.45.0b10, 3.45.0b11, 3.45.0b12, 3.45.0b13, 3.45.0, 3.45.1, 3.45.2, 3.46.0, 3.46.1, 3.47.0, 3.47.1, 3.48.0, 3.49.0, 3.50.0, 3.50.1, 3.50.2, 4.0.0b15, 4.0.0, 4.0.1, 4.0.2, 4.1.0, 4.1.1, 4.1.2, 4.2.0, 4.3.0, 4.4.0, 4.4.1, 4.5.0, 4.7.0, 4.7.1, 4.8.0, 4.9.0, 4.9.1, 4.10.0, 4.11.0, 4.12.0, 4.13.0, 4.14.0, 4.15.0, 4.16.0, 4.17.0, 4.18.0, 4.19.0, 4.19.1, 4.19.2, 4.20.0, 4.20.1, 4.21.0, 4.22.0, 4.23.0, 4.24.0, 4.25.0, 4.26.0, 4.27.0, 4.28.0, 4.28.1, 4.28.2, 4.28.3, 4.29.0, 4.31.0, 4.31.1, 4.31.2, 4.31.3, 4.31.4, 4.31.5, 4.32.0, 4.32.1, 4.32.2, 4.33.0, 4.35.0, 4.36.0, 4.36.1, 4.37.1, 4.37.2, 4.38.0, 4.38.1, 4.39.0, 4.40.0, 4.41.0, 4.42.0, 4.43.0, 4.44.0, 4.44.1, 5.0.0b1, 5.0.0b5, 5.0.0b6, 5.0.0b7, 5.0.0b8, 5.0.0b9, 5.0.0b10, 5.0.0, 5.0.1, 5.0.2, 5.1.0, 5.3.0, 5.4.0, 5.5.0)
24.29 ERROR: No matching distribution found for gradio==5.0.0b4
------

 **2 warnings found (use docker --debug to expand):
 - JSONArgsRecommended: JSON arguments recommended for CMD to prevent unintended behavior related to OS signals (line 60)
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 58)
Dockerfile:45
--------------------
  43 |     
  44 |     RUN echo "Installing requirements.txt"
  45 | >>> RUN pip3 install --no-cache-dir --upgrade -r /code/requirements.txt
  46 |     
  47 |     # yeah.. this is manual for now
--------------------
ERROR: failed to solve: process "/bin/sh -c pip3 install --no-cache-dir --upgrade -r /code/requirements.txt" did not complete successfully: exit code: 1**

Why is it failing?

**Comment by jbilcke-hf** [comment]
It seems to be an issue with Gradio 5, the version indicated in the requirements.txt was `gradio===5.0.0b4" but for some reason the Gradio team removed it from PyPI 

I will replace it with "gradio===5.6.0"

**Comment by jbilcke-hf** [comment]
I've pushed the update and build the code on Hugging Face

you can now pull the fix from github @somenewaccountthen to update the code
